#index:
#    path: /
#    controller: App\Controller\DefaultController::index

page:
  resource: '@PageBundle/Resources/config/routes.yml'
  prefix: '/page'

other:
  resource: '@OtherBundle/Resources/config/routes.yml'
  prefix: '/other'
